[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.147.2"  # Use your Hugo version

[dev]
  command = "hugo server -D --bind 0.0.0.0"
  port = 8888
  targetPort = 1313
  autoLaunch = false
  host = "0.0.0.0"

[functions]
  directory = "netlify/functions"
